<div class="row">
    <div class="actions text-center">
        <button class="view-more-button primary" title="<?= __('View More Products'); ?>"><?= __('View More Products'); ?></button>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".product-items": {
            "SuttonSilver_InfiniteScroll/js/iscroll": {"nextClass":".pages-item-next .next","paginationClass":".toolbar-products"}
        }
    }
</script>